name: CI

on:
    - push
    - pull_request

concurrency:
    group: ci
    cancel-in-progress: true

jobs:
    install:
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v4

            - name: Install packages
              run: pnpm i

    format:
        needs: install
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v4
            - name: Install packages
              run: pnpm i

            - name: Check formatting
              run: pnpm format:check

    lint:
        needs: install
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v4
            - name: Install packages
              run: pnpm i

            - name: Check linting
              run: pnpm lint

            - name: TypeScript Check
              run: pnpm ts-check
